{% set name = "mathpad" %}
{% set version = "2.0.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mathpad-{{ version }}.tar.gz
  sha256: 8f87a16c63ee68d351a9d9c25c639afbd72849a3ebe75c211e14609f4a8c9a1e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - pip
    - python >=3.6,<3.10
    - poetry
  run:
    # - k3d >=2.15.2,<3.0.0
    - numpy >=1.20,<2.0
    - plotly >=5.3.1,<6.0.0
    - python >=3.6,<3.10
    - scipy >=1.7.1,<2.0.0
    - sympy >=1.8,<2.0
    - tqdm >=4.62.3,<5.0.0
    - typing-extensions >=4.0.0,<5.0.0

test:
  imports:
    - mathpad
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CallumJHays/mathpad
  summary: Simplified interface to Sympy for solving physics, engineering and maths problems
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CallumJHays
